### PR TITLE
cloud-canary: add more sleep in between instance creation and ssh

### PR DESCRIPTION
**Pull request by LaCap**
In order to avoid the alerts of last night.
Adding a bit delay between instance creation and first ssh attempt.

### CODE REVIEW

**Comment by marcaurele** [comment]
A must have!

**Comment by llambiel** [comment]
@LaCap @marcaurele This should be considered as a temp trick. The canary time being measured it add a significant penalty here. I prefer having a loop that exit with error after x try

**Comment by jpmenil** [comment]
There is already a 60s time in the while loop.
According to the canary vm logs, sshd daemon was not started when the script tried the ssh connection.

**Comment by LaCap** [comment]
@llambiel do you mean we are using this script to store some measurement of performance for deployment too?
If it's the case would it be better to have a separate one?

**Comment by llambiel** [comment]
@LaCap yes https://graph.internal.exoscale.ch/grafana/dashboard/db/open-cloud?refresh=5m&panelId=8&fullscreen&orgId=1

Ideally it should be handled using the same script instead of having multiple to do almost the same job

**Pull request merged**
